name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        jdk: [17]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Run tests and build with Gradle
        run: |
          if [ "$RUNNER_OS" != "Windows" ]; then
              chmod a+x gradlew
              ./gradlew build
          else
            ./gradlew.bat build
          fi
        shell: bash
